services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    container_name: node-app
    restart: always
    build: .
    volumes: ['./:/usr/src/app']
    ports:
      - '3000:3000'
    links:
      - redis
   